import type Theme from './theme'
// your interface path

const lightTheme: Theme = {
  dark: false,
  colors: {
    background: '#F5F3FF',
    surface: '#FFFFFF',
    'surface-bright': '#EDE9FE',
    'surface-light': '#F5F3FF',
    'surface-variant': '#DDD6FE',
    'on-surface-variant': '#4C1D95',
    primary: '#6D28D9',
    'primary-darken-1': '#4C1D95',
    secondary: '#A855F7',
    'secondary-darken-1': '#7E22CE',
    error: '#DC2626',
    info: '#2563EB',
    success: '#16A34A',
    warning: '#D97706',
  },
  variables: {
    'border-color': '#6D28D9',
    'border-opacity': 0.12,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.6,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.08,
    'focus-opacity': 0.12,
    'selected-opacity': 0.12,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.16,
    'dragged-opacity': 0.08,
    'theme-kbd': '#1A1033',
    'theme-on-kbd': '#EDE9FE',
    'theme-code': '#EDE9FE',
    'theme-on-code': '#4C1D95',
  },
}

const darkTheme: Theme = {
  dark: true,
  colors: {
    background: '#0F0A1E',
    surface: '#1A1033',
    'surface-bright': '#2D1B69',
    'surface-light': '#1A1033',
    'surface-variant': '#2D1B69',
    'on-surface-variant': '#DDD6FE',
    primary: '#7C3AED',
    'primary-darken-1': '#5B21B6',
    secondary: '#C084FC',
    'secondary-darken-1': '#A855F7',
    error: '#EF4444',
    info: '#3B82F6',
    success: '#22C55E',
    warning: '#F59E0B',
  },
  variables: {
    'border-color': '#7C3AED',
    'border-opacity': 0.24,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.6,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.06,
    'hover-opacity': 0.1,
    'focus-opacity': 0.14,
    'selected-opacity': 0.14,
    'activated-opacity': 0.14,
    'pressed-opacity': 0.18,
    'dragged-opacity': 0.1,
    'theme-kbd': '#EDE9FE',
    'theme-on-kbd': '#1A1033',
    'theme-code': '#2D1B69',
    'theme-on-code': '#DDD6FE',
  },
}

export { lightTheme, darkTheme }
